import type { Metadata } from "next";
import { EB_Garamond,Poppins} from "next/font/google";
import "./globals.css";

const ebgaramond = EB_Garamond({
  variable: "--font-eb-garamond",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"], 
  weight: ["400", "500", "600", "700"] ,
});

export const metadata: Metadata = {
  title: "Candra Sedana",
  description: "Generated by create Kamapra",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="id"
      className={`${ebgaramond.variable} ${poppins.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
